POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Sanjeev Rai",
    "username": "@sanjeevrai015"
}
###

POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
    "userId": 1,
    "blogId": 2
}